#!/bin/bash
wppath='/usr/share/webapps/wordpress'
htuser='http'
htgroup='http'
rootuser='root'

printf "chmod Files and Directories\n"
find ${wppath}/ -xdev -type f -print0 | xargs -0 chmod 0640
find ${wppath}/ -xdev -type d -print0 | xargs -0 chmod 0750

printf "chown Directories\n"
find ${wppath}/ -xdev -exec chown ${htuser}:${htgroup} {} \;
chmod 640 ${wppath}/index.php

printf "chmod/chown .htaccess\n"
if [ -f ${wppath}/.htaccess ]
 then
  chmod 0644 ${wppath}/.htaccess
  chown ${rootuser}:${htgroup} ${wppath}/.htaccess
fi
