---
- name: set up dlyg database
  command: /usr/local/rvm/bin/rvm {{ dlyg_ruby }}@{{ dlyg_gemset }} do bundle exec rake db:setup
  args:
      chdir: "{{ dlyg_dir }}"
  environment:
      RAILS_ENV: production

- name: install dlyg gems
  bundler:
      chdir: "{{ dlyg_dir }}"
      clean: yes
      deployment_mode: yes
      state: present

- name: ensure the dlyg log file exists
  file:
      path: "{{ dlyg_dir }}/log/production.log"
      owner: dlyg
      group: dlyg
      mode: 0664
      state: touch

- name: run dlyg database migrations
  command: /usr/local/rvm/bin/rvm {{ dlyg_ruby }}@{{ dlyg_gemset }} do bundle exec rake db:migrate
  args:
      chdir: "{{ dlyg_dir }}"
  environment:
      RAILS_ENV: production

- name: precompile dlyg assets
  command: /usr/local/rvm/bin/rvm {{ dlyg_ruby }}@{{ dlyg_gemset }} do bundle exec rake assets:precompile
  args:
      chdir: "{{ dlyg_dir }}"
  environment:
      RAILS_ENV: production
