---
- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: reload httpd
  service:
      name: httpd
      state: reloaded

- name: restart httpd
  service:
      name: httpd
      state: restarted

- name: restart ddclient
  service:
      name: ddclient
      state: restarted

- name: restart airsonic
  docker_container:
      name: airsonic
      restart: yes
      state: started
