---
- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: reload httpd
  service:
      name: httpd
      state: reloaded

- name: restart httpd
  service:
      name: httpd
      state: restarted

- name: install personae gems
  bundler:
      chdir: "{{ personae_dir }}"
      clean: yes
      deployment_mode: yes
      state: present
