---
- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: reload httpd
  service:
      name: httpd
      state: reloaded

- name: restart httpd
  service:
      name: httpd
      state: restarted

- name: reload lighttpd
  systemd:
      name: lighttpd
      state: reloaded

