#!/usr/bin/env ansible-playbook
---
- import_playbook: storage.yml
- import_playbook: base.yml
- import_playbook: dnsserver.yml
- import_playbook: mailserver.yml
- import_playbook: docker.yml
- import_playbook: dbserver.yml
- import_playbook: webserver.yml
