#!/usr/bin/env ansible-playbook
---
- hosts: all:!storage
  tasks:
      - name: system updates
        pacman:
            upgrade: yes
            update_cache: yes
            state: present
        register: updates
        tags:
            - always

      - name: re-exec systemd if needed
        command: /usr/bin/systemctl daemon-reexec
        when: '"systemd" in updates.packages'

      - name: restart iptables if needed
        systemd:
            name: "{{ item }}"
            state: restarted
            daemon_reload: yes
        when: '"iptables" in updates.packages'
        with_items:
            - iptables
            - ip6tables

      - name: restart openssh if needed
        systemd:
            name: sshd
            state: restarted
            daemon_reload: yes
        when: ('openssh' in updates.packages) or
              ('openssl' in updates.packages)

      - name: restart nfs services if needed
        systemd:
            name: "{{ item }}"
            state: restarted
            daemon_reload: yes
        when: ('nfs-utils' in updates.packages) or
              ('rpcbind' in updates.packages)
        with_items:
            - rpcbind
            - nfs-client.target
            - remote-fs.target
            - systemd-networkd-wait-online

      - name: set wordpress permissions if needed
        command: /usr/local/bin/wp-perms
        when: '"wordpress" in updates.packages'

      - name: set nextcloud permissions if needed
        command: /usr/local/bin/set-nc-perms
        when: '"nextcloud" in updates.packages'

      - name: restart httpd if needed
        systemd:
            name: httpd
            state: restarted
            daemon_reload: yes
        when: ('apache' in updates.packages) or
              ('passenger' in updates.packages) or
              ('php' in updates.packages) or
              ('php-apache' in updates.packages) or
              ('php-apcu-bc' in updates.packages) or
              ('php-gd' in updates.packages) or
              ('php-intl' in updates.packages) or
              ('php-mcrypt' in updates.packages) or
              ('openssl' in updates.packages) or
              ('wordpress' in updates.packages)

      - name: restart other services if needed
        systemd:
            name: "{{ item }}"
            state: restarted
            daemon_reload: yes
        when: item in updates.packages
        with_items:
            - cronie
            - fake-hwclock
            - mariadb
            - ddclient
            - dnsmasq
            - opendkim
            - postfix
            - spamassassin
            - docker
