---
- name: install dovecot and pigeonhole (sieve)
  pacman:
      name: "{{ item }}"
      state: installed
  with_items:
      - dovecot
      - pigeonhole
  tags:
      - dovecot

- name: configure dovecot
  copy:
      src: files/dovecot/dovecot.conf
      dest: /etc/dovecot/dovecot.conf
      owner: root
      group: root
      mode: 0644
  notify: reload dovecot
  tags:
      - dovecot

- name: configure dovecot standard configs
  file:
      src: /usr/share/doc/dovecot/example-config/conf.d/{{ item }}
      dest: /etc/dovecot/conf.d/{{ item }}
      state: link
  with_items:
      - 10-director.conf
      - 10-master.conf
      - 15-mailboxes.conf
      - 20-imap.conf
      - 20-pop3.conf
      - 90-acl.conf
      - 90-plugin.conf
      - 90-quota.conf
      - auth-checkpassword.conf.ext
      - auth-deny.conf.ext
      - auth-dict.conf.ext
      - auth-ldap.conf.ext
      - auth-master.conf.ext
      - auth-passwdfile.conf.ext
      - auth-sql.conf.ext
      - auth-static.conf.ext
      - auth-system.conf.ext
      - auth-vpopmail.conf.ext
  notify: reload dovecot
  tags:
      - dovecot

- name: configure dovecot non-standard configs
  copy:
      src: files/dovecot/conf.d/{{ item }}
      dest: /etc/dovecot/conf.d/{{ item }}
      owner: root
      group: root
      mode: 0644
  with_items:
      - 10-auth.conf
      - 10-mail.conf
      - 15-lda.conf
      - 20-lmtp.conf
      - 80-sieve.conf
  notify: reload dovecot
  tags:
      - dovecot

- name: configure dovecot customized configs
  template:
      src: templates/dovecot/conf.d/{{ item }}.j2
      dest: /etc/dovecot/conf.d/{{ item }}
      owner: root
      group: root
      mode: 0644
  with_items:
      - 10-ssl.conf
  notify: reload dovecot
  tags:
      - dovecot

- name: ensure dovecot is started
  service:
      name: dovecot
      enabled: yes
      state: started
  tags:
      - dovecot
