---
- name: install postfix
  pacman:
      name: postfix
      state: installed
  tags:
      - postfix

- name: configure postfix
  template:
      src: templates/postfix/main.cf.j2
      dest: /etc/postfix/main.cf
      owner: root
      group: root
      mode: 0644
  notify: reload postfix
  tags:
      - postfix

- name: configure postfix daemon
  copy:
      src: files/postfix/master.cf
      dest: /etc/postfix/master.cf
      owner: root
      group: root
      mode: 0644
  notify: restart postfix
  tags:
      - postfix

- name: generate dhparams
  command: /usr/bin/openssl dhparam -out /etc/postfix/dhparams.pem 2048
  args:
      creates: /etc/postfix/dhparams.pem
  notify: restart postfix
  tags:
      - postfix

- name: configure aliases
  lineinfile:
      dest: /etc/postfix/aliases
      regexp: "^(?:#)?root:\\s+\\S+"
      line: "root:          {{ user }}"
      backrefs: yes
      owner: root
      group: root
      mode: 0644
  notify: run newaliases
  tags:
      - postfix

- name: ensure postfix is started
  service:
      name: postfix
      enabled: yes
      state: started
  tags:
      - postfix
