---
- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: reload sshd
  service:
      name: sshd
      state: reloaded

- name: reload iptables
  service:
      name: iptables
      state: reloaded

- name: compile sieve rules
  command: /usr/bin/sievec /home/{{ user }}/.dovecot.sieve /home/{{ user }}/.dovecot.svbin
  become: "{{ user }}"
