---
- name: enable tcp forwarding
  sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
  tags:
      - vpn

- name: install openvpn
  pacman:
      name: "{{ item }}"
      state: installed
  with_items:
      - openvpn
      - easy-rsa
  tags:
      - vpn

- name: create clean easyrsa pki
  shell: easyrsa init-pki
  args:
      chdir: /etc/easy-rsa/
      creates: /etc/easy-rsa/pki
  tags:
      - vpn

- name: create easyrsa ca
  expect:
    command: easyrsa build-ca nopass
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/ca.crt
    responses:
        Common Name: 'Easy-RSA CA'
  register: result
  tags:
      - vpn

- name: copy openvpn ca cert into place
  command: cp /etc/easy-rsa/pki/ca.crt /etc/openvpn/server/ca.crt
  when: result|changed
  tags:
      - vpn

- name: create DH params file
  command: openssl dhparam -out /etc/openvpn/server/dh2048.pem 2048
  args:
      creates: /etc/openvpn/server/dh2048.pem
  tags:
      - vpn

- name: create HMAC key
  command: openvpn --genkey --secret /etc/openvpn/server/ta.key
  args:
      creates: /etc/openvpn/server/ta.key
  tags:
      - vpn

- name: create openvpn server cert csr/key
  expect:
    command: easyrsa gen-req void.yuggoth.space nopass
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/reqs/void.yuggoth.space.req
    responses:
        Common Name: 'void.yuggoth.space'
  tags:
      - vpn

- name: sign openvpn server cert
  expect:
    command: easyrsa sign-req server void.yuggoth.space
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/issued/void.yuggoth.space.crt
    responses:
        Confirm request details: 'yes'
  register: result
  tags:
      - vpn

- name: copy openvpn server cert into place
  command: cp /etc/easy-rsa/pki/issued/void.yuggoth.space.crt /etc/openvpn/server/server.crt
  when: result|changed
  tags:
      - vpn

- name: copy openvpn server key into place
  command: cp /etc/easy-rsa/pki/private/void.yuggoth.space.key /etc/openvpn/server/server.key
  when: result|changed
  tags:
      - vpn

- name: create openvpn client cert csr/key
  expect:
    command: easyrsa gen-req client1 nopass
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/reqs/client1.req
    responses:
        Common Name: 'client1'
  tags:
      - vpn

- name: create second openvpn client cert csr/key
  expect:
    command: easyrsa gen-req client2 nopass
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/reqs/client2.req
    responses:
        Common Name: 'client2'
  tags:
      - vpn

- name: sign openvpn client cert
  expect:
    command: easyrsa sign-req client client1
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/issued/client1.crt
    responses:
        Confirm request details: 'yes'
  tags:
      - vpn

- name: sign second openvpn client cert
  expect:
    command: easyrsa sign-req client client2
    chdir: /etc/easy-rsa/
    creates: /etc/easy-rsa/pki/issued/client2.crt
    responses:
        Confirm request details: 'yes'
  tags:
      - vpn

- name: land the openvpn server config
  template:
      src: templates/openvpn/server.conf.j2
      dest: /etc/openvpn/server/server.conf
      owner: root
      group: root
      mode: 660
  notify: restart openvpn
  tags:
      - vpn

- name: enable IP forwarding
  sysctl:
      name: net.ipv4.ip_forward
      value: 1
      state: present
  tags:
      - vpn

- name: ensure openvpn is running
  service:
      name: openvpn-server@server
      enabled: yes
      state: started
  tags:
      - vpn
