---
- name: reload systemd
  command: /usr/bin/systemctl daemon-reload

- name: restart ddclient
  service:
      name: ddclient
      state: restart

- name: reload dnsmasq
  service:
      name: dnsmasq
      state: reloaded
