---
- name: mount mariadb storage
  mount:
      src: "{{ storage_host }}:{{ db_volume }}"
      name: "{{ db_mountpoint }}"
      fstype: nfs
      opts: vers=3,comment=systemd.automount
      dump: 0
      passno: 0
      state: mounted
  tags:
      - database
      - storage

- name: install mariadb (and python connectors)
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - mariadb
      - mysql-python
  tags:
      - database

- name: ensure mariadb systemd override directory exists
  file:
      path: /etc/systemd/system/mariadb.service.d
      owner: root
      group: root
      mode: 0755
      state: directory
  tags:
      - database

- name: land mariadb systemd override
  template:
      src: templates/mariadb/override.conf.j2
      dest: /etc/systemd/system/mariadb.service.d/override.conf
      owner: root
      group: root
      mode: 0644
  notify: reload systemd
  tags:
      - database

- name: ensure mariadb is running
  systemd:
      name: mariadb
      enabled: yes
      state: started
  tags:
      - database

- name: set mariadb root password
  mysql_user:
      name: root
      password: "{{ db_root_password }}"
      state: present
  ignore_errors: True
  tags:
      - database

- name: land mariadb credentials files
  ini_file:
      dest: "{{ item.path }}"
      section: client
      option: password
      value: "{{ db_root_password }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
      mode: 0600
      state: present
  with_items:
      - { path: '/root/.my.cnf', owner: 'root', group: 'root' }
      - { path: '/etc/my-extra.cnf', owner: 'mysql', group: 'mysql' }
  tags:
      - database

- name: remove the anonymous mariadb user
  mysql_user:
      name: ''
      state: absent
  tags:
      - database
