---
- name: install dnsmasq
  pacman:
      name: dnsmasq
      state: present
  tags:
      - dnsmasq

- name: configure dnsmasq
  template:
      src: templates/dnsmasq/dnsmasq.conf.j2
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644
  notify: reload dnsmasq
  tags:
      - dnsmasq

- name: ensure dnsmasq is running
  systemd:
      name: dnsmasq
      enabled: yes
      state: started
  tags:
      - dnsmasq
