---
- name: install pi-hole dependencies
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - bc
    - lighttpd
  tags:
    - pi-hole

- name: land the pi-hole dnsmasq config
  copy:
    src: files/dnsmasq/dnsmasq.d/01-pihole.conf
    dest: /etc/dnsmasq.d/01-pihole.conf
    owner: root
    group: root
    mode: 0644
  notify: reload dnsmasq
  tags:
    - pi-hole
    - dnsmasq

- name: configure pi-hole FTL
  template:
    src: templates/pi-hole/pihole-FTL.conf.j2
    dest: /etc/pihole/pihole-FTL.conf
    owner: root
    group: root
    mode: 0644
  notify: restart pi-hole-ftl
  tags:
    - pi-hole
    - pi-hole-ftl
