---
- name: run newaliases
  command: /usr/bin/newaliases

- name: reload postfix
  service:
      name: postfix
      state: reloaded

- name: reload dovecot
  service:
      name: dovecot
      state: reloaded
