---
- name: install docker
  pacman:
    name:
      - docker
      - python-docker
    state: installed
  tags:
    - docker

- name: check kernel type
  command: pacman -Qqs linux kernel and modules
  register: kernel_type
  tags:
    - docker

- name: mount docker volume storage
  mount:
    src: "{{ storage_host }}:{{ docker_volumes }}"
    name: "{{ docker_mountpoint }}"
    fstype: nfs
    opts: vers=3,comment=systemd.automount
    dump: 0
    passno: 0
    state: mounted
  when: "'raspberrypi' not in kernel_type and 'odroid' not in kernel_type"
  notify: restart docker
  tags:
    - docker
    - storage

- name: ensure docker daemon is running
  systemd:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
