---
- name: install docker
  pacman:
    name:
      - docker
      - python-docker
    state: installed
  tags:
    - docker

- name: check kernel type
  command: pacman -Qqs linux kernel and modules
  register: kernel_type
  tags:
    - docker

- name: ensure docker daemon is running
  systemd:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker
