---
- name: land iptables config
  copy:
      src: files/iptables/iptables.rules
      dest: /etc/iptables/iptables.rules
      owner: root
      group: root
      mode: 0644
  notify: reload iptables
  tags:
      - firewall

- name: ensure iptables is running
  systemd:
      name: iptables
      enabled: yes
      state: started
  tags:
      - firewall
