---
- name: configure locale.gen
  lineinfile:
      dest: /etc/locale.gen
      regexp: "^#en_US.UTF-8 UTF-8\\s*$"
      backrefs: yes
      line: "en_US.UTF-8 UTF-8"
      owner: root
      group: root
      mode: 0644
      state: present
  notify: regen locale
  tags:
      - locale
