---
- name: install nfs utils
  pacman:
      name: "{{ item }}"
      state: installed
  with_items:
      - nfs-utils
      - rpcbind
  tags:
      - nfs

- name: ensure nfs client services are started
  systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
  with_items:
      - rpcbind
      - nfs-client.target
      - remote-fs.target
      - systemd-networkd-wait-online
  tags:
      - nfs
