---
- name: install standard tools
  pacman:
      name: "{{ item }}"
      state: installed
  with_items:
      - archey3
      - bash-completion
      - bind-tools
      - git
      - gnu-netcat
      - vim
  tags:
      - std-utils
