---
- name: set timezone
  command: /usr/bin/timedatectl set-timezone America/New_York
  tags:
      - timedate
  when: ansible_date_time.tz != 'EDT' and ansible_date_time.tz != 'EST'

- name: install fake-hwclock
  pacman:
      name: fake-hwclock
      state: present
  tags:
      - timedate
      - fake-hwclock

- name: ensure fake-hwclock is running
  service:
      name: fake-hwclock
      enabled: yes
      state: started
  tags:
      - timedate
      - fake-hwclock

- name: set fake-hwclock timer
  service:
      name: fake-hwclock-save.timer
      enabled: yes
  tags:
      - timedate
      - fake-hwclock
