---
- name: ensure private group is present
  group:
      name: "{{ user }}"
      gid: "{{ gid }}"
      state: present
  tags:
      - user

- name: ensure user is present
  user:
      name: "{{ user }}"
      uid: "{{ uid }}"
      group: "{{ user }}"
      groups: 'wheel'
      state: present
  tags:
      - user

- name: land authorized key for user
  authorized_key:
      user: "{{ user }}"
      key: "{{ item }}"
      state: present
  with_file:
      - files/id_rsa.pub
  tags:
      - user
