---
- name: ensure private group is present
  group:
      name: "{{ user }}"
      gid: "{{ gid }}"
      state: present
  tags:
      - user

- name: ensure user is present
  user:
      name: "{{ user }}"
      uid: "{{ uid }}"
      group: "{{ user }}"
      groups: 'wheel'
      state: present
  tags:
      - user

- name: land authorized key for user
  authorized_key:
      user: "{{ user }}"
      key: "{{ item }}"
      state: present
  with_file:
      - files/id_rsa.pub
  tags:
      - user

- name: land archey3 config
  copy:
      name: files/user/archey3.cfg
      dest: /home/{{ user }}/.archey3.cfg
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: 0644
  tags:
      - user

- name: install sudo
  pacman:
      name: sudo
      state: installed
  tags:
      - user
      - sudo

- name: ensure wheel group can use sudo
  lineinfile:
      dest: /etc/sudoers
      regexp: "^# %wheel ALL=\\(ALL\\) ALL$"
      line: "%wheel ALL=(ALL) ALL"
      backrefs: yes
      validate: 'visudo -cf %s'
      owner: root
      group: root
      mode: 0440
      state: present
  tags:
      - user
      - sudo
