---
- name: install docker
  pacman:
      name:
        - docker
        - python-docker
      state: present
  tags:
      - docker

- name: ensure docker is running
  systemd:
      name: docker
      enabled: yes
      state: started
  tags:
      - docker

- name: create airsonic persistent storage
  docker_volume:
      name: "{{ item }}"
      state: present
  with_items:
      - airsonic_data
      - airsonic_music
      - airsonic_playlists
      - airsonic_podcasts
  tags:
      - airsonic
      - docker

- name: mount nfs for music
  mount:
      src: "{{ storage_host }}:{{ as_music_volume }}"
      name: "{{ as_music_volume_mountpoint }}"
      fstype: nfs
      opts: vers=3,x-systemd.wanted-by=multi-user.target,x-systemd.automount
      dump: 0
      passno: 0
      state: mounted
  tags:
      - airsonic
      - storage

- name: land airsonic config
  template:
      src: templates/airsonic/airsonic.properties.j2
      dest: /var/lib/docker/volumes/airsonic_data/_data/airsonic.properties
      owner: root
      group: root
      mode: 0644
  notify: restart airsonic
  tags:
      - airsonic

- name: ensure airsonic is running
  docker_container:
      name: airsonic
      image: "airsonicadvanced/airsonic-advanced"
      container_default_behavior: no_defaults
      auto_remove: false
      detach: true
      init: no
      interactive: no
      memory: "0"
      paused: no
      privileged: no
      read_only: no
      tty: no
      volumes:
        - airsonic_data:/var/airsonic
        - airsonic_music:/var/music
        - airsonic_playlists:/var/playlists
        - airsonic_podcasts:/var/podcast
      pull: true
      published_ports:
        - "{{ airsonic_port }}:{{ airsonic_port }}"
      restart_policy: always
      env:
        JAVA_OPTS='-Xmx1g'
  tags:
    - airsonic
    - container

- name: land httpd airsonic config
  template:
      src: templates/httpd/extra/airsonic.conf.j2
      dest: /etc/httpd/conf/extra/airsonic.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - airsonic
      - httpd
