---
- name: create dlyg mariadb database
  mysql_db:
      name: "{{ dlyg_dbname }}"
      state: present
  tags:
      - dlyg
      - database

- name: create dlyg mariadb user
  mysql_user:
      name: "{{ dlyg_dbuser }}"
      host: '%'
      password: "{{ dlyg_dbpassword }}"
      priv: "{{ dlyg_dbname }}.*:ALL"
      state: present
  tags:
      - dlyg
      - database

- name: ensure the dlyg image is running
  docker_container:
      name: dlyg
      image: yithian/dlyg-arm64v8
      env:
        OPENSHIFT_APP_NAME: "{{ dlyg_dbname }}"
        OPENSHIFT_MYSQL_DB_USERNAME: "{{ dlyg_dbuser }}"
        OPENSHIFT_MYSQL_DB_PASSWORD: "{{ dlyg_dbpassword }}"
        OPENSHIFT_MYSQL_DB_HOST: "{{ ansible_docker0.ipv4.address }}"
      published_ports: "{{ dlyg_port}}:9292"
      restart_policy: always
      pull: true
      state: started
  tags:
      - dlyg
      - docker

- name: land the dlyg httpd config
  template:
      src: templates/httpd/extra/dlyg.conf.j2
      dest: /etc/httpd/conf/extra/dlyg.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - dlyg
      - httpd
