---
- name: install docker tools
  pacman:
      name: "{{ item }}"
      state: present
  with_items:
      - docker
      - python2-docker
  tags:
      - docker

- name: ensure docker is running
  service:
      name: docker
      enabled: true
      state: started
  tags:
      - docker
