---
- name: install node
  pacman:
    name: 'nodejs'
    state: present
  tags:
      - foundry

- name: set up foundry group
  group:
    name: 'foundryvtt'
    system: yes
    state: present
  tags:
    - foundry

- name: set up foundry user
  user:
    name: 'foundryvtt'
    group: 'foundryvtt'
    shell: '/sbin/nologin'
    home: '/opt/foundryvtt'
    system: yes
    state: present
  tags:
    - foundry

- name: set up foundry dirs
  file:
    dest: "/opt/{{ item }}"
    owner: 'foundryvtt'
    group: 'foundryvtt'
    mode: 0775
    state: directory
  with_items:
    - 'foundryvtt'
    - 'foundrydata'
  tags:
    - foundry

- name: mount foundry storage volume
  mount:
    src: "{{ storage_host }}:{{ foundry_volume }}"
    name: "{{ foundry_mountpoint }}"
    fstype: nfs
    opts: vers=3,comment=systemd.automount
    dump: 0
    passno: 0
    state: mounted
  tags:
      - foundry
      - storage

- name: land foundry service
  copy:
    src: files/foundry/foundry.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: 0644
  tags:
    - foundry

- name: ensure foundry is running
  systemd:
    name: foundry
    enabled: yes
    state: started
  tags:
    - foundry

- name: land httpd foundry config
  template:
      src: templates/httpd/extra/foundry.conf.j2
      dest: /etc/httpd/conf/extra/foundry.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - foundry
      - httpd
