---
- name: install vsftpd
  pacman:
      name: vsftpd
      state: installed
  tags:
      - ftp

- name: create the ftpsecure user
  user:
      name: ftpsecure
      shell: /bin/nologin
      system: yes
  tags:
      - ftp

- name: land the vsftpd config
  template:
      src: templates/vsftpd/vsftpd.conf.j2
      dest: /etc/vsftpd.conf
      owner: root
      group: root
      mode: 0644
  notify: reload vsftpd
  tags:
      - ftp

- name: ensure vsftpd is running
  service:
      name: vsftpd
      state: started
  tags:
      - ftp
