---
- name: install httpd
  pacman:
      name: apache
      state: installed
  tags:
      - httpd

- name: land core httpd config
  template:
      src: templates/httpd/httpd.conf.j2
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - httpd

- name: ensure httpd is started
  service:
      name: httpd
      enabled: yes
      state: started
  tags:
      - httpd
