---
- name: create nextcloud mariadb database
  mysql_db:
      name: "{{ nc_dbname }}"
      state: present
  tags:
      - nextcloud
      - database

- name: create nextcloud mariadb user
  mysql_user:
      name: "{{ nc_dbuser }}"
      password: "{{ nc_dbpassword }}"
      priv: "{{ nc_dbname }}.*:ALL"
      state: present
  tags:
      - nextcloud
      - database

- name: install nextcloud
  pacman:
      name: nextcloud
      state: present
  tags:
      - wordpress

- name: mount nextcloud storage
  mount:
      src: "{{ storage_host }}:{{ nc_volume }}"
      name: "{{ nc_mountpoint }}"
      fstype: nfs
      opts: _netdev,vers=3
      dump: 0
      passno: 0
      state: mounted
  tags:
      - nextcloud
      - storage

- name: ensure httpd systemd override directory exists
  file:
      path: /etc/systemd/system/httpd.service.d
      owner: root
      group: root
      mode: 0755
      state: directory
  tags:
      - nextcloud

- name: land httpd systemd override
  template:
      src: templates/httpd/override.conf.j2
      dest: /etc/systemd/system/httpd.service.d/override.conf
      owner: root
      group: root
      mode: 0644
  notify: reload systemd
  tags:
      - nextcloud

- name: land the set-nc-perms script
  copy:
    src: files/nextcloud/set-nc-perms
    dest: /usr/local/bin/set-nc-perms
    owner: root
    group: root
    mode: 0755
  tags:
      - nextcloud

- name: set nextcloud permissions
  command: /usr/local/bin/set-nc-perms runtime
  tags:
      - nextcloud

- name: configure nextcloud
  template:
      src: templates/nextcloud/config.php.j2
      dest: /etc/webapps/nextcloud/config/config.php
      owner: http
      group: http
      mode: 0640
  become_user: http
  notify: restart httpd
  tags:
      - nextcloud

- name: cron nextcloud's cron.php
  cron:
      name: nextcloud cron.php
      user: http
      minute: "*/15"
      job: php -f /usr/share/webapps/nextcloud/cron.php > /dev/null 2>&1
      state: present
  tags:
      - nextcloud
      - cron

- name: configure nextcloud httpd virtual host
  template:
      src: templates/httpd/extra/nextcloud.conf.j2
      dest: /etc/httpd/conf/extra/nextcloud.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - nextcloud
      - httpd
