---
- name: install rails tools
  pacman:
      name: "{{ item }}"
      state: installed
  with_items:
      - ruby
      - ruby-bundler
      - passenger
      - nodejs
  tags:
      - passenger
      - personae
