---
- name: create personae mariadb database
  mysql_db:
      name: "{{ personae_dbname }}"
      state: present
  tags:
      - personae
      - database

- name: create personae mariadb user
  mysql_user:
      name: "{{ personae_dbuser }}"
      host: '%'
      password: "{{ personae_dbpassword }}"
      priv: "{{ personae_dbname }}.*:ALL"
      state: present
  tags:
      - personae
      - database

- name: ensure the personae image is running
  docker_container:
      name: personae
      image: yithian/personae-arm64v8
      env:
        OPENSHIFT_APP_NAME: "{{ personae_dbname }}"
        OPENSHIFT_MYSQL_DB_USERNAME: "{{ personae_dbuser }}"
        OPENSHIFT_MYSQL_DB_PASSWORD: "{{ personae_dbpassword }}"
        OPENSHIFT_MYSQL_DB_HOST: "{{ ansible_docker0.ipv4.address }}"
      published_ports: "{{ personae_port}}:9292"
      restart_policy: always
      pull: true
      state: started
  tags:
      - personae
      - docker

- name: land the personae httpd config
  template:
      src: templates/httpd/extra/personae.conf.j2
      dest: /etc/httpd/conf/extra/personae.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - personae
      - httpd
