---
- name: install php (and other requirements)
  pacman:
      name: "{{ item }}"
      state: installed
  with_items:
      - php
      - php-apache
      - php-apcu-bc # optional by nextcloud
      - php-gd # required by nextcloud
      - php-intl # recommended by nextcloud
      - php-mcrypt # recommended by nextcloud
  notify: restart httpd
  tags:
      - php
      - nextcloud
      - wordpress

- name: configure php
  copy:
      src: files/php/php.ini
      dest: /etc/php/php.ini
      owner: root
      group: root
      mode: 0644
  notify: restart httpd
  tags:
      - php
      - nextcloud
      - wordpress

- name: configure apcu
  copy:
      src: files/php/conf.d/apcu.ini
      dest: /etc/php/conf.d/apcu.ini
      owner: root
      group: root
      mode: 0644
  notify: restart httpd
  tags:
      - php
      - nextcloud
