---
- name: land pi-hole httpd virtual host
  template:
    src: templates/httpd/extra/pi-hole.conf.j2
    dest: /etc/httpd/conf/extra/pi-hole.conf
    owner: root
    group: root
    mode: 0644
  notify: reload httpd
  tags:
    - pi-hole
    - httpd

- name: land the pi-hole lighttpd config
  template:
    src: templates/lighttpd/lighttpd.conf.j2
    dest: /etc/lighttpd/lighttpd.conf
    owner: root
    group: root
    mode: 0644
  notify: reload lighttpd
  tags:
    - pi-hole
    - lighttpd

- name: start lighttpd for pi-hole
  systemd:
    name: lighttpd
    state: started
    enabled: yes
  tags:
    - pi-hole
    - lighttpd
