---
- name: create roundcube mariadb database
  mysql_db:
      name: "{{ rc_dbname }}"
      state: present
  tags:
      - roundcube
      - database

- name: create roundcube mariadb user
  mysql_user:
      name: "{{ rc_dbuser }}"
      password: "{{ rc_dbpassword }}"
      priv: "{{ rc_dbname }}.*:ALL"
      state: present
  tags:
      - roundcube
      - database

- name: install roundcube
  pacman:
      name: roundcubemail
      state: installed
  notify: restart httpd
  tags:
      - roundcube

- name: configure roundcube
  template:
      src: templates/roundcube/config.inc.php.j2
      dest: /etc/webapps/roundcubemail/config/config.inc.php
      owner: root
      group: root
      mode: 0644
  notify: restart httpd
  tags:
      - roundcube

- name: configure roundcube httpd virtual host
  template:
      src: templates/httpd/extra/roundcube.conf.j2
      dest: /etc/httpd/conf/extra/roundcube.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - roundcube
      - httpd
