---
- name: install openssl
  pacman:
      name: openssl
      state: installed
  tags:
      - ssl

- name: land httpd ssl config
  template:
      src: templates/httpd/extra/httpd-ssl.conf.j2
      dest: /etc/httpd/conf/extra/httpd-ssl.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - httpd
      - ssl
