---
- name: create wordpress mariadb database
  mysql_db:
      name: "{{ wordpress_dbname }}"
      state: present
  tags:
      - wordpress
      - database

- name: create wordpress mariadb user
  mysql_user:
      name: "{{ wordpress_dbuser }}"
      password: "{{ wordpress_dbpassword }}"
      priv: "{{ wordpress_dbname }}.*:ALL"
      state: present
  tags:
      - wordpress
      - database

- name: install wordpress
  pacman:
      name: wordpress
      state: present
  tags:
      - wordpress

- name: land the wp-perms script
  copy:
      src: files/wordpress/wp-perms
      dest: /usr/local/bin/wp-perms
      owner: root
      group: root
      mode: 0755
  tags:
      - wordpress

- name: set wordpress permissions
  command: /usr/local/bin/wp-perms
  tags:
      - wordpress

- name: configure wordpress
  template:
      src: templates/wordpress/wp-config.php.j2
      dest: /usr/share/webapps/wordpress/wp-config.php
      owner: http
      group: http
      mode: 0640
  notify: restart httpd
  tags:
      - wordpress

- name: land the wordpress httpd config
  template:
      src: templates/httpd/extra/wordpress.conf.j2
      dest: /etc/httpd/conf/extra/wordpress.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - wordpress
      - httpd
