---
- name: configure www httpd virtual host
  template:
      src: templates/httpd/extra/www.conf.j2
      dest: /etc/httpd/conf/extra/www.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - www
