---
- name: mount www storage
  mount:
      src: "{{ storage_host }}:{{ www_volume }}"
      name: "{{ www_mountpoint }}"
      fstype: nfs
      opts: vers=3,comment=systemd.automount
      dump: 0
      passno: 0
      state: mounted
  tags:
      - www
      - storage

- name: configure www httpd virtual host
  template:
      src: templates/httpd/extra/www.conf.j2
      dest: /etc/httpd/conf/extra/www.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - www
