---
- name: install certbot
  pacman:
      name:
          - certbot
          - certbot-apache
          - certbot-dns-cloudflare
      state: installed
  tags:
      - ssl

- name: land Cloudflare creds file
  ini_file:
      path: "{{ cloudflare_creds_file }}"
      mode: 0600
      owner: root
      group: root
      section: null
      option: dns_cloudflare_api_token
      value: "{{ cloudflare_api_token }}"
      state: present
  tags:
      - dns
      - cloudflare

- name: register with Let's Encrypt if necessary
  command: /usr/bin/certbot register -n -m {{ user }}@{{ domain }} --agree-tos
  args:
      creates: /etc/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/*
  tags:
      - ssl

- name: get a Let's Encrypt cert if necessary
  command: /usr/bin/certbot certonly -n --dns-cloudflare --dns-cloudflare-credentials {{ cloudflare_creds_file }} --preferred-challenges dns-01 -d {{ domain }},*.{{ domain }} --cert-name {{ ssl_cert_name }}
  args:
      creates: {{ ssl_cert_file }}
  tags:
      - ssl

- name: renew ssl certs every month
  cron:
      name: renew ssl certs every month
      minute: 8
      hour: 0
      weekday: 0
      job: systemctl stop httpd && certbot renew && systemctl start httpd
  tags:
      - ssl
      - cron
