---
- name: ensure the znc volume is ready
  docker_volume:
    name: "{{ znc_docker_volume }}"
    state: present
  tags:
    - docker
    - znc

- name: update the znc certs after renewal
  template:
    src: templates/letsencrypt/renewal-hooks/post/znc_update.sh.j2
    dest: /etc/letsencrypt/renewal-hooks/post/znc_update.sh
    owner: root
    group: root
    mode: 744
  tags:
    - ssl
    - znc

- name: run the znc container
  docker_container:
    name: "{{ znc_container_name }}"
    image: arm64v8/znc
    pull: yes
    restart_policy: always
    published_ports:
      - "{{ znc_port }}:6697"
    volumes:
      - "{{ znc_docker_volume }}:/znc-data"
  tags:
    - docker
    - znc
