#!/bin/bash
ocpath='/usr/share/webapps/owncloud'
htuser='http'
htgroup='http'
rootuser='root'

printf "Creating possible missing Directories\n"
mkdir -p $ocpath/data
mkdir -p $ocpath/assets

printf "chmod Files and Directories\n"
find ${ocpath}/ -xdev -type f -print0 | xargs -0 chmod 0640
find ${ocpath}/ -xdev -type d -print0 | xargs -0 chmod 0750

printf "chown Directories\n"
# nfs is going to cause trubs
#chown -R ${rootuser}:${htgroup} ${ocpath}/
find ${ocpath}/ -xdev -exec chown ${rootuser}:${htgroup} {} \;
chown -R ${htuser}:${htgroup} ${ocpath}/apps/
chown -R ${htuser}:${htgroup} ${ocpath}/config/
# nfs won't let us change these perms anyway
#chown -R ${htuser}:${htgroup} ${ocpath}/data/
chown -R ${htuser}:${htgroup} ${ocpath}/themes/
chown -R ${htuser}:${htgroup} ${ocpath}/assets/

chmod +x ${ocpath}/occ

printf "chmod/chown .htaccess\n"
if [ -f ${ocpath}/.htaccess ]
 then
  chmod 0644 ${ocpath}/.htaccess
  chown ${rootuser}:${htgroup} ${ocpath}/.htaccess
fi
if [ -f ${ocpath}/data/.htaccess ]
 then
  su http -s /bin/bash -c "chmod 0644 ${ocpath}/data/.htaccess"
  # nfs won't let us do this
  #chown ${rootuser}:${htgroup} ${ocpath}/data/.htaccess
fi
