---
- name: create pihole persistent storage
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
    - pihole_etc
    - pihole_dnsmasq
  tags:
    - pihole
    - docker

- name: mount nfs for pihole etc
  mount:
    src: "{{ storage_host }}:{{ pihole_etc_volume }}"
    name: "{{ pihole_etc_mountpoint }}"
    fstype: nfs
    opts: vers=3,comment=systemd.automount
    dump: 0
    passno: 0
    state: mounted
  tags:
    - docker
    - pihole

- name: mount nfs for pihole dnsmasq
  mount:
    src: "{{ storage_host }}:{{ pihole_dnsmasq_volume }}"
    name: "{{ pihole_dnsmasq_mountpoint }}"
    fstype: nfs
    opts: vers=3,comment=systemd.automount
    dump: 0
    passno: 0
    state: mounted
  tags:
    - docker
    - pihole

- name: disable systemd-resolved stub listener
  lineinfile:
      path: /etc/systemd/resolved.conf
      regexp: "#?DNSStubListener=yes"
      line: "DNSStubListener=no"
      state: present
  notify:
      - restart systemd-resolved
  tags:
      - systemd

- name: create a pihole container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    restart_policy: always
    pull: true
    published_ports:
      - "53:53/tcp" # DNS
      - "53:53/udp" # DNS
      #- "67:67/udp" # DHCP
      - "{{ pihole_web_port }}:80/tcp" # HTTP
    env:
      TZ: "America/New_York"
      # opendns upstream
      PIHOLE_DNS_: 1.1.1.1;1.0.0.1
      WEBPASSWORD: "{{ pihole_admin_password }}"
      PIHOLE_DOMAIN: "{{ pihole_host }}"
      VIRTUAL_HOST:  "{{ pihole_host }}"
    volumes:
      - "{{ pihole_etc_volume }}:/etc/pihole/"
      - "{{ pihole_dnsmasq_volume }}:/etc/dnsmasq.d/"
    restart_policy: unless-stopped
    dns_servers:
      - 127.0.0.1
      - 1.1.1.1
  tags:
    - pihole
    - container

- name: land httpd pihole config
  template:
      src: templates/httpd/extra/pihole.conf.j2
      dest: /etc/httpd/conf/extra/pihole.conf
      owner: root
      group: root
      mode: 0644
  notify: reload httpd
  tags:
      - pihole
      - httpd
