---
- name: pull pihole docker image
  docker_image:
    name: pihole/pihole:latest
    source: pull
    state: present
  tags:
    - pihole
    - docker

- name: create pihole persistent storage
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
    - pihole_etc
    - pihole_dnsmasq
  tags:
    - pihole
    - docker

- name: mount pihole volumes
  docker_volume:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_pihole_etc_volume }}"
    - "{{ docker_pihole_dnsmasqd_volume }}"
  tags:
    - docker
    - pihole

- name: ensure systemd-resolved is not running
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no

- name: create a pihole container
  docker_container:
    name: pihole
    image: pihole/pihole:latest
    state: started
    restart_policy: always
    published_ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    env:
      TZ: "America/New_York"
      # opendns upstream
      PIHOLE_DNS_: 208.67.222.222;208.67.220.220
      PIHOLE_DOMAIN: # fill in
      VIRTUAL_HOST: # fill in
    volumes:
      - "{{ docker_pihole_etc_volume }}:/etc/pihole/"
      - "{{ docker_pihole_dnsmasqd_volume }}:/etc/dnsmasq.d/"
    restart_policy: unless-stopped
    dns_servers:
      - 127.0.0.1
      - 208.67.222.222
  tags:
    - pihole
    - container
